name: Publish LabAide to Maven repository
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: |
            [{
              "id": "reposilite-repository",
              "username": "${{ secrets.REPO_NAME }}",
              "password": "${{ secrets.REPO_TOKEN }}"
            }]
      - name: Publish with Maven
        run: mvn deploy -X
